---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: instance
    immage: geerlingguy/docker-centos8-ansible:latest
    command: ""
    volume:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
